name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest